--- #YAML:1.0
name:               MooseX-Types-GTIN
version:            0.01
abstract:           ~
author:
    - Dave Lambley <davel@state51.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Find:       0
    File::Spec:       0
    Test::Exception:  0
    Test::More:       0
requires:
    Moose:                0
    MooseX::Types::Moose:  0
resources:
    repository:  https://github.com/davel/MooseX-Types-GTIN
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
